LP-816 | Update UI Flutter
veryfi/veryfi-lens-flutter-demo pull request #54
Opened 2024-01-04 22:09 UTC by sevasvalveryfi

**Description**
- Please, let's conduct a thorough review of our app and update everything related to the UI, ensuring consistency in colors, fonts, shadows, and background colors.

**Solution**
- This Pr add new UI Design for Flutter project
- Add multiple documents Scanning options
- New loading animation
- New Extracted data format UI
- New JsonViewer format UI

**Evidences**
- ![mainmenu](https://github.com/veryfi/veryfi-lens-flutter-demo/assets/148891377/8c7d534c-d522-46ff-845c-4f75c7e4b35c)
- ![loading](https://github.com/veryfi/veryfi-lens-flutter-demo/assets/148891377/2d69dce6-e38c-4f78-a19e-e68de885d806)
- ![extracted](https://github.com/veryfi/veryfi-lens-flutter-demo/assets/148891377/e8c86665-fdb9-4910-88c0-2e0029908de9)
- ![json](https://github.com/veryfi/veryfi-lens-flutter-demo/assets/148891377/8f08188b-9bb5-4369-a4e7-ad6c4e1bfcdc)

**Notes**
- This Pr closes LP-816 Jira ticket project

2024-01-04 22:23 UTC, alejouribesanchez requested changes
launcher icon should be keep it

2024-01-04 22:26 UTC, beresmo commented
some feedback:

> Tabs

- no following the green color
- No consistency between lowercase and uppercase

> Card views

- No following background color

2024-01-04 22:30 UTC, beresmo commented
- Missing receipt preview screenshot
- Missing settings screenshot
- How do I navigate after scanning a receipt?
- The extracted data should be left and right, left the tag and right the information.

2024-01-04 22:32 UTC, beresmo commented
What does dark mode look like?

2024-01-04 22:33 UTC, decim92 commented
We don't need anything related to other non mobile platforms like web, linux or macOS files or folders

2024-01-04 22:34 UTC, decim92 commented
Please upload at least one screenshot of running in iOS simulator

2024-01-04 22:36 UTC, decim92 commented on .gitignore
> -.env
I see we're still using dotenv so why this line about ignoring `.env` file should not be removed

2024-01-04 22:41 UTC, decim92 commented
I'd rather have all new widgets in individual files, instead of a massive `main.dart` file

2024-01-04 22:45 UTC, decim92 commented on .gitignore
> -pubspec.lock
This one also should be ignored, unless there's something that forces us to upload it, the `pubspec.yaml` will define latest dependencies versions (or if you want specific versions, they should be defined in the `pubspec.yaml`
Also don't forget to remove `pubspec.lock` from git history

2024-01-11 19:31 UTC, sevasvalveryfi commented on .gitignore
> -pubspec.lock
Done

2024-01-11 19:31 UTC, sevasvalveryfi commented on .gitignore
> -.env
Done

2024-01-11 19:32 UTC, sevasvalveryfi commented
> I'd rather have all new widgets in individual files, instead of a massive `main.dart` file

Only Android is part of this scope, for another side, i need setting up all IOS env for flutter like xcode cocoapods ans so on, for now is Android

2024-01-11 19:54 UTC, sevasvalveryfi commented
> We don't need anything related to other non mobile platforms like web, linux or macOS files or folders

Done

2024-01-11 20:01 UTC, sevasvalveryfi commented
> launcher icon should be keep it

Done

2024-01-11 20:14 UTC, beresmo approved these changes

2024-01-11 23:41 UTC, closed without merging